### ISSUE TITLE
Add notice about SCSS-Lint

### ISSUE THREAD

**Issue by elektronik2k5** [Famolus/awesome-sass#28]
`scss-lint`'s [readme](https://github.com/brigade/scss-lint#notice-consider-other-tools-before-adopting-scss-lint) starts with:
> **NOTICE: Consider other tools before adopting SCSS-Lint**

> The Sass core team is now building Sass in Dart instead of Ruby, and will no longer be maintaining the Ruby implementation unless a maintainer steps up to help. Since the SCSS-Lint project relies on the Ruby Sass implementation, this means it will eventually not support the latest Sass features and bug fixes.

> Two alternatives worthy of consideration are stylelint and sass-lint, with sass-lint having closer feature parity to SCSS-lint.

> The SCSS-Lint project will continue to accept pull requests and provide basic support on the issue tracker.

I suggest we add a short note next to the list entry:
- [scss-lint](https://github.com/brigade/scss-lint) - Configurable tool for writing clean and consistent SCSS. *[Not recommended](https://github.com/brigade/scss-lint#notice-consider-other-tools-before-adopting-scss-lint), consider [stylelint](https://stylelint.io/) instead.*

**Comment by tandavas** [comment]
Good idea!

How about we add `deprecated` instead? like:

- [scss-lint](https://github.com/brigade/scss-lint) - Configurable tool for writing clean and consistent SCSS. *[(deprecated)](https://github.com/brigade/scss-lint#notice-consider-other-tools-before-adopting-scss-lint)*

What do you think?

**Comment by elektronik2k5** [comment]
Sure, I'm make a PR later today :)
