### ISSUE TITLE
Remove some broken link

### ISSUE THREAD

**Issue by jokosusilo** [Famolus/awesome-sass#38]
Hey, i just checked this repo and find some of link are broken.

- Kaliber - https://github.com/robbinfellow/kaliber
This link is broken because the repo has been removed

- edX Sass and CSS Style Guide - https://github.com/edx/ux-pattern-library/wiki/Styleguide:-Sass-&-CSS
This guide has been deprecated, see https://github.com/edx/ux-pattern-library/wiki/Styleguide:-General

So, can I create a PR to remove that link or you'll remove it by yourself? :smile:

**Comment by tandavas** [comment]
Sure! Go ahead and create a PR. Thank you for the heads up! 🎉

**Comment by tandavas** [comment]
Thank you again!

**Comment by jokosusilo** [comment]
You're welcome :tada:
