### ISSUE TITLE
Alphabetise frameworks & libraries

### ISSUE THREAD

**Issue by CupOfTea696** [Famolus/awesome-sass#54]
I was just thinking it might be a good idea to alphabetise frameworks & libraries as to not imply any bias over which ones are better. I'm willing to make a PR but just checking in first if you'd want that cuz it'd be a shame to put in the effort for nothing ;p

**Comment by tandavas** [comment]
That'd be freaking awesome! It will be a lot easier for people to browse and search for something in the list.

Go for it 😉👍
